### ISSUE TITLE
4.1.0_setup.ipynbのheadコマンドについて

### ISSUE THREAD

**Issue by tokuma09** [tksakaki/kspub_ds_text_analytics#1]
著者の皆様　大変参考になる書籍を出版いただきありがとうございます。

書籍を参考に4.1.0_setup.ipynbを自分で動かしていたところ、headコマンドについてエラーが出ましたので、解決策を含めて情報を共有させていただきます。

## 環境
macOS Monterey 12.2

一般にmacOSで起こり得る問題かと思います。

## 発生事象
以下のコードにてエラーが発生。
```bash
!tail -n +18 text/kageotoko.stripruby.txt | head -n -14 > text/kageotoko.corpus.txt
!head text/kageotoko.corpus.txt
```
エラー状況は以下の通り。
```bash
head: illegal line count -- -14
tail: stdout: Broken pipe
```

## 原因

macOSの場合`head`, `tail`がUNIXベースでGNU配布のものではないため、引数に負値を許容しない設定になっている。

## 解決方法

homebrewにて`coreutils`をインストール
```bash
brew install coreutils
```
`tail`, `head`をそれぞれ`gtail`, `ghead`に変更(GNU配布のものを利用)
```bash
!gtail -n +18 text/kageotoko.stripruby.txt | ghead -n -14 > text/kageotoko.corpus.txt
!ghead text/kageotoko.corpus.txt
```
で解決しました。

Macユーザーで起こり得る事象かと思いますので、情報共有させていただきました。

**Comment by kobayakawa-t-ko** [comment]
ありがとうございます。
ご指摘の通り、macOSのhead,tailコマンドは、GNU配布のものを用いないとサンプルが動作しません。
`brew link coreutils`
を実行していただくと、gの付かないコマンド名で実行できますので、サンプルがそのまま動作するようになります。
coreutilsのインストール後に実行していただく必要がありますので、次のようにします。
```
brew install coreutils
brew link coreutils
```

本書籍p52や、このgithubリポジトリの

- [kspub_ds_text_analytics/Chapter03/setup_python.md](https://github.com/tksakaki/kspub_ds_text_analytics/blob/main/Chapter03/setup_python.md#macos)
- [よくあるトラブルについて](https://github.com/tksakaki/kspub_ds_text_analytics/blob/main/Others/Troubleshooting.md)

に記載してございます。

また、`brew link coreutils`を実行すると、head,tailだけでなく他のGNU配布ツールもgのつかない状態で実行できるようになってしまいます。MacOS標準のものを使わないといけない事情がある場合は、次のいずれかの方法で使い分けができます。
いずれの方法も一長一短ございますので、環境に合わせた方法をご選択ください。

- brew link coreutilsを実行せずに、GNU 配布ツールを使う場合にgを先頭につける。例えば、ghead,gtail,gls。
- brew link coreutilsを実行し、macOSツールを使う場合はフルパスで指定する。例えば、/usr/bin/head,/usr/bin/tail,/bin/ls。

なお、一旦 `brew link coreutils`を実行した場合でも、 `brew unlink coreutils`を実行することで元に戻すことができます。

**Comment by tokuma09** [comment]
すでによくあるトラブルとしてあったということで失礼致しました。
補足いただきありがとうございます。　こちらに関してはcloseさせていただきます。
