### ISSUE TITLE
Pyenvのインストールが出来なかったため、教えていただけますでしょうか？

### ISSUE THREAD

**Issue by mihsato** [tksakaki/kspub_ds_text_analytics#3]
WindowsPCへの環境構築でつまずいております。
私の理解不足による質問となってしまうかもしれないのですが、2点ほど確認させていただけますでしょうか？

①
下記URLに倣い、Pyenvのインストールを試みたのですが、
https://github.com/tksakaki/kspub_ds_text_analytics/blob/main/Chapter03/setup_pyenv.md
下記コマンドが実行できませんでした。
## pyenvのインストール
$ git clone https://github.com/pyenv/pyenv.git ~/.pyenv

Command 'get' not found, but there are 18 similar ones.
というエラーが出ていたのですが、どのように修正すれば良いでしょうか？

②また、githubでは、上記コマンドに続いて、
「## .bash_profileへの書き込み」というタイトルで３つのコマンドが掲載されていましたが、
物理本の59ページ目には書かれていたコマンドは全く別のものでした。
どちらが正しいコマンドになりますでしょうか。。？

お手数をおかけしますが、ご教示のほど、どうぞよろしくお願いいたします。

**Comment by tksakaki** [comment]
> $ git clone https://github.com/pyenv/pyenv.git ~/.pyenv
> Command 'get' not found, but there are 18 similar ones.
> というエラーが出ていたのですが、どのように修正すれば良いでしょうか？
エラーメッセージを見ると、 `git` ではなくて、 `get` というコマンドを実行したように見えます。
↓自分の環境で `get` を実行した際のエラーメッセージ
```
$ get
Command 'get' not found, but there are 18 similar ones.
```
typoかもしれないので，再度確認の上，

**Comment by tksakaki** [comment]
> ①
> $ git clone https://github.com/pyenv/pyenv.git ~/.pyenv
> Command 'get' not found, but there are 18 similar ones.
> というエラーが出ていたのですが、どのように修正すれば良いでしょうか？

エラーメッセージを見ると、 `git` ではなくて、 `get` というコマンドを実行したように見えます。
↓自分の環境で `get` を実行した際のエラーメッセージ
```
$ get
Command 'get' not found, but there are 18 similar ones.
```
typoかもしれないので，再度入力コマンド確認の上、実行してみてください。


> ②また、githubでは、上記コマンドに続いて、
>「## .bash_profileへの書き込み」というタイトルで３つのコマンドが掲載されていましたが、
> 物理本の59ページ目には書かれていたコマンドは全く別のものでした。
> どちらが正しいコマンドになりますでしょうか。。？

pyenvのインストール方法は，想定している環境によって少しずつ異なってきます。
ので、書籍が想定している環境によって「正しいコマンド」が異なります。
本書では「bashというシェルが用いられ，その設定ファイルが.bash_profileであるという場合」を想定しています．
またpyenvのバージョンが新しくなると、同じ環境でもインストール方法が変更されることもあります。

ただ、WSLのUbuntu20.04のデフォルト設定は本書の想定と一致するはずなので、
本書のインストール方法でうまくいくと思います。

本書のインストール方法でうまく行かない場合、
https://github.com/pyenv/pyenv の `Installation` の項目をご確認ください。
そちらを見て頂くことが一番確実です。

（ちょっとわかりにくいのですが、p.59の脚注(4)に同様の内容が書かれています）

**Comment by mihsato** [comment]
さっそくご回答いただき、ありがとうございました！
①は、typoによるエラーとのこと、大変失礼致しました。再度試してみます。
②については、本に記載されているコマンドを試してみます。

ありがとうございました！
